### ISSUE TITLE
Content debugging

### ISSUE THREAD

**Issue by Khaledgarbaya** [contentful/contentful-metalsmith#24]
As a user I would like to have a way of debugging/log the content that is being rendered.
this could be tackled in two ways:
- Having a debug flag if true the plugin will log some data on the rendered page
- having a log helper that the users can use

**Comment by stefanjudis** [comment]
I think the log helper might be a better solution here? But I don't mind. 

¯\_(ツ)_/¯

**Comment by radiovisual** [comment]
I am constantly trying to debug/log data that comes back from Contentful. My current approach is sortof messy/hacky, but it works: I built a handlebars helper called `stringify` which lets me temporarily print out data that is seen by my templates.

So I just need to add this to my templates:

```js
{{ stringify data.fields.foo }}
// or
{{ stringify this }}
```
and then I get a temporary dump of the data into the templates. But it would be awesome if we could inspect the data returned by Contentful without having to dump data into the templates, so I vote for the logging idea.

**Comment by stefanjudis** [comment]
@radiovisual Did you check this 👉  https://github.com/contentful/contentful-metalsmith#debugging?

I just quickly tried but this works fine here.

```
DEBUG=metalsmith-contentful-files DEBUG_DEPTH=5 npm test    
```

**Comment by radiovisual** [comment]
> @radiovisual Did you check this 👉 https://github.com/contentful/contentful-metalsmith#debugging?

Yes, that actually works rather well in regards to the formatting. Problem for me is that it also produces a lot of noise. Because it gives me EVERYTHING, I have to scroll through a lot of noise to get to what is relevant for my debugging. It would be nice if there was a way to focus the output a little more.

Like, if I could debug a single template:

<pre>
---
title: Test
contentful:
  entry_id: abc123
  debug: true
layout: layout-speakers-page.html
---
</pre>

or somehow limit the debugging output to specific content_types:

```
DEBUG=metalsmith-contentful-files 'my-file-here' DEBUG_DEPTH=5 <command>
```

**Comment by stefanjudis** [comment]
What about something like 

```
DEBUG=metalsmith-contentful-files DEBUG-FILE'my-file-here.html DEBUG_DEPTH=5 <command>
```

This is clashing a bit with the `DEBUG` prefix, but I might make sense? Any opinions?

It would also be fairly easy to implement 👉  https://github.com/contentful/contentful-metalsmith/blob/master/index.js#L47 A single check here is probably enough.

cc. @axe312ger

**Comment by radiovisual** [comment]
I like this:

```
DEBUG=metalsmith-contentful-files DEBUG-FILE=my-file-here.html DEBUG_DEPTH=5 <command>
```

I agree it clashes a bit with the `DEBUG` prefix, but `DEBUG-FILE` is a very specific name, so for my tastes, I don't feel any immediate objections nor do I foresee any namespace issues. 😃

**Comment by axe312ger** [comment]
I help myself to debug Metalsmith with the following tricks:

1. helper class for `metalsmith-layouts` to output data properly to html: https://github.com/axe312ger/metalsmith-webpack-suite/blob/master/src/scripts/metalsmith.js#L35

2. using `DEBUG=metalsmith*` gives a lot of information, since the debug module is pretty common in the metalsmith universe

3. add your own little debug plugin, could look like:
```js
metalsmith.use((files, metalsmith, done) => {
  console.log(JSON.stringify(files, null, 2))
  done()
})
```

**Comment by leviwheatcroft** [comment]
Take a look at [metalsmith-debug-ui](https://github.com/leviwheatcroft/metalsmith-debug-ui) (shameless self plug.. sorry). Basically renders your files and meta in html as a collapsible tree, you can skip forwards or backwards to view the data at any time during the build process.

I'm not sure this would directly address @Khaledgarbaya 's question re: debugging *content*, because I couldn't figure out how best to render the actual content of files. Very open to suggestions.

That said, this plugin is perfect for a lot of the other use cases in this thread.. writing everything to the console get's a bit unweildy. 

![debug-ui](http://leviwheatcroft.github.io/metalsmith-debug-ui/images/files.png)

**Comment by Khaledgarbaya** [comment]
This great, thank y'all for the nice tools.
I am closing the issue for now
